logging:
  level: INFO

marketdata:
  depth: 20

walls:
  top_n_levels: 5
  candidate_ratio_to_median: 12.0
  candidate_max_distance_ticks: 2
  confirm_dwell_seconds: 3.0
  confirm_max_distance_ticks: 1
  consume_window_seconds: 3.0
  consume_drop_pct: 25.0
  teleport_reset: true

debug:
  walls_enabled: false
  walls_interval_seconds: 1.0
